### ISSUE TITLE
Why not be able to compile with Android Studio?

### ISSUE THREAD

**Issue by NanyangTaiji** [PowerExplorer/PowerFileExplorer#1]

**Comment by PowerExplorer** [comment]
I don't have pc to use Android Studio. I'm using AIDE for Android phone.
This is my hobby app

**Comment by PowerExplorer** [comment]
I don't have pc to use Android Studio. I'm using AIDE for Android phones. 
Maybe you have to create an empty app on Android Studio first. And then copy java, res... to proper folder, and also copy some dependencies in gradle file.

**Comment by NanyangTaiji** [comment]
THANKS!

**Comment by NanyangTaiji** [comment]
DO you have apk so I can test first?

**Comment by masudr4n4** [comment]
I need the apk file too to test test it.or when releasing new versions  pls add apk file to release  page.

**Comment by ckysmrn** [comment]
> I don't have pc to use Android Studio. I'm using AIDE for Android phones. Maybe you have to create an empty app on Android Studio first. And then copy java, res... to proper folder, and also copy some dependencies in gradle file.

FYI: 
if you have no pc, you can install java and gradle on [Termux](https://github.com/termux/termux-app) 
also you can use git, gh (for github action/codespace), cmake command and what ever that on termux..
so many people can contribute
